# Generated by Django 4.0 on 2021-12-27 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='user',
        ),
        migrations.AddField(
            model_name='text',
            name='send_to',
            field=models.ManyToManyField(related_name='user_rec', to=settings.AUTH_USER_MODEL),
        ),
    ]
